### ISSUE TITLE
Ability to move players between servers

### ISSUE THREAD

**Issue by Oppossome** [sboxgame/issues#1456]
### What can't you do?
While the lobby system is wonderful, it will not and should not try to cover every use case. There needs to be ways to move players between sessions so we are able to manage, spin up, and control our own servers using **_our own_** infrastructure. 

### How it would be used
Something that allows us to grab the current server's address or identifier eg. `Host.GetIP()`
A way to send a player elsewhere eg. `Client.SendTo( address )`

### Actual games that utilize this
*World of Warcraft / Final Fantasy XIV*
Players are moved between sub-servers that manage specific regions as to make players able to see others in the same region.

*VRChat / Second Life*
Players move between sessions as they please with the ability to have arbitrary people join them from the session. For example, dropping a portal for a group of people. 

*Tower Unite / GMod Tower*
There's a global game queue that anyone can enter and once the required players are hit, they are moved to a spun up server and subsequently moved back to their sessions after it's complete.

*Roblox / Minecraft Servers utilizing Plugins*
Developers are enabled to move players between sessions as they please allowing for games of large scopes that are too big for single session scopes. 

*Dark Souls*
Players are able to invade each other's worlds based on arbitrary criteria. 

### Why I feel this is justified
It would allow for large standalone games on the platform to exist that wouldn't benefit from simply having a lobby system. The only workaround at the moment is web sockets but the trade off that comes with it is immense and would require several systems to be rebuilt from scratch.

**Comment by Rohansi** [comment]
Some function to redirect a player to a specific server would be good however this needs more thought. None of the examples you listed can be accomplished with just a `Client.SendTo( address )` call. Additional systems would be required depending on the game:
* Persistent player state across servers
* Matchmaking queues
* Maintaining player state when being sent to another server (health, where they came from, etc.)
* Inter-server networking (synchronizing game events, chat across servers, etc.)
* Preventing players from joining more than one server at a time
* Probably more!

We cannot reasonably have all of that built into S&box because they will be far too specific for the gamemode. So I just think it's important to remember that there can still be a lot of work required to accomplish your goals even though you wouldn't need to drop down to WebSockets.

I think the following are required at a minimum:
1. A way to approve/deny/redirect player connections before joining the game
    * Should be `async` so it can call on an external service
2. A function to make the client connect to a different server
    * Should disconnect from the current server of course, and then immediately connect to the given server address

And maybe additionally:

3. A way to connect a few players to a new lobby
    * For some matchmaking, pulls X players into a new lobby hosting a specific gamemode

**Comment by Oppossome** [comment]
Well of course, but I am just asking for the bare minimum so we can create our own infrastructure on our side to enable these systems to work. I do not expect facepunch to attempt to make a solution that works for everything, all I want is the ability to facilitate these things on my side. The hardest part of setting up this infrastructure should not be whether or not I can move a player between servers.
