### ISSUE TITLE
Add a default Keybind for Inventory Systems to use

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#1477]
**What can't you do?**
I'd like to have a keybind players can use in my gamemode to open their inventory. On a QWERTY keyboard I imagine this being the 'I' key.

**How would you like it to work?**
Just add something like InputButton.Inventory

I imagine this being common enough between gamemodes to warrant it having a unified keybind.

I'd also like to have a keybind for something like toggling night vision, but I'm not sure what a great solution for that is, since it's pretty niche.

**What have you tried?**
Custom binds, but they're a chore.

**Additional context**
matt told me to post an issue

**Comment by DevulTj** [comment]
I don't get why you need **another key** for inventories, when you have InputButton.Score (TAB on Keyboard) and also InputButton.Menu (Q on Keyboard)

**Comment by Fortune117** [comment]
What if you wanted to add an inventory to something like sandbox, where both those binds are already taken. 

You could make do another way, but it's such a common gameplay element I don't see the harm in it.

**Comment by DevulTj** [comment]
Inventory's probably okay, I'm more focused on making sure these work on kbm and controllers.

DPad Up or something on Controller.

**Comment by ogniK5377** [comment]
How would this map to a controller?

**Comment by mzegar** [comment]
It'll be hard to justify adding any additional keys since you'll be asked to either...
1. Create a UI element that incorporates multiple actions that opens using a single already existing keybind
2. Use a key combination of already existing keybindings

There have been multiple issues before created asking to expose additional keybindings as well
https://github.com/Facepunch/sbox-issues/issues/196
https://github.com/Facepunch/sbox-issues/issues/1014
https://github.com/Facepunch/sbox-issues/issues/1016
https://github.com/Facepunch/sbox-issues/issues/1178

The FacePunch devs can correct me, but their current goal is to ensure that there is a strict limited definition of keys so that the keyboard and controller are functional for all game modes. 

Personally, I disagree since I'm assuming the goal of s&box is to be essentially a game engine. A game engine should give the option for developers to not support controllers, make dumb keybindings decisions, etc. If s&box is trying to be like a "game maker" instead, I guess it makes sense to restrict keybindings and create a more "controlled" and "unified" "game maker".
