### ISSUE TITLE
New Asset Browser - Add a proper search bar

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#2005]
### What can't you do?

Right now in the new asset browser it's a mess when it comes to the search feature, it's all stockpiled in the entire bar stuck between absolute paths to the current folder, filters & the actual search.

e.g `"c:/program files (x86)/steam/steamapps/common/sbox/core/materials/dev/simple/" t:vmat floor`

![image](https://user-images.githubusercontent.com/67245359/177182067-e7469ecb-3863-4ed3-bf56-0ccbcf491ab2.png)

### How would you like it to work?

I feel like it should have a dedicated path bar that is using a relative path rather than an absolute, then the search bar should be its own text entry and could also have an history dropdown.

![image](https://user-images.githubusercontent.com/67245359/177184094-cb48aabe-90b2-454f-8375-4fd6d4166959.png)

![image](https://user-images.githubusercontent.com/67245359/177184111-e014daa4-0544-4df6-8a00-233f0b6a6363.png)

**Comment by garrynewman** [comment]
I don't think that's a great solution. The intention of the search bar is to become something like this..

![image](https://user-images.githubusercontent.com/928843/177185198-d2422eee-3b7d-4c8c-bc52-7d836f3b7cf8.png)

Once it's like that elements like absolute paths can be shortened, and different types of filter (types, folder, age, changed, filesize, text search) can be colored different to make them more distinct from each other.

Having a single bar, and a single line of text that filters the asserts is purposeful and important. It's what allows the back/forward mouse button history and it allows you to quickly search using your keyboard instead of clicking/tabbing around a bunch of different boxes.

**Comment by KayaDLX** [comment]
I see how that would work now, it's like Discord's search feature, I didn't understand at first as it's in a half finished state where you have to type it manually for now.

![image](https://user-images.githubusercontent.com/67245359/177189078-37617105-da8d-4034-92e5-d67c5b1a311f.png)

I still think the path should still be shortened though, and maybe `t:` should be more explicit and be `type:`
e.g: "`addon: core` `materials/dev/simple` `type: vmat + vmdl` floor"

Adding color code or even icons would work well as a substitute to the old dropdown tickbox thing (especially if the tags persist when you reopen s&box), I'm fine with either.

I'll let this open in case other people have anything to say about this planned feature.

**Comment by KayaDLX** [comment]
Yeah that's a good point, let's say I wanna quickly search through my stuff and use `CTRL+A` then `BACKSPACE` to quickly delete my old search while still willing to keep my working addon & desired asset tags, I feel like this could be separated in two text entries between tags & actual search terms rather than all in one (or maybe that's just tied to my old workflow but I feel like that's what most people will end up doing by habits, especially Hammer users that don't switch tags & working folders all the time).

**Comment by NotGaylien** [comment]
it would be cool if we can get (as Hannah Montana once said) "The best of both worlds"
in regards to having the tags, but also being able to do that delete all and quick search again.

**Comment by xezno** [comment]
Quixel's search uses this system and it makes it a lot harder to quickly switch between different searches imo

**Comment by NotGaylien** [comment]
I just want to add this extra.

I am ok with the tag filters, but i much rather them not flood the search bar, currently what i do with the legacy browser is something along the lines of this
![image](https://user-images.githubusercontent.com/82092361/180086350-6eb14d22-e0dd-49a8-b4d0-e319b0d808e5.png)

I dont want to have this as my search bar.

[VMDL] + [VMDL_PREFAB] + [VMAT]  + [VSNAP] + [VPCF] + [VSND] + [VMAP] + [VANMGRPH] + [JPG] Lamp

Just to search for lamps, I don't want to be deleting tags and adding them back constantly as well, i rather select what i need, and then let searching "Lamp" do the work. its ALOT faster than having to search [VMDL] + [VMAT] + [JPG] Lamp.
for each sort of different assets types i want to search (i usually need to be messing with multiple different asset types).
___ 
And then  also, 
Just because i saw it mentioned in discord that its not that hard to use folders.

the way that works best, at least from my time using this stuff is,
selecting the project and flattening hierarchy, it makes searching for specific things so much better.
For example i need to work on my lamp assets.
Sweet i just search "Lamp" and they are right there in a split second, rather not go through folders to try get to each of them, that makes working on them a lot lot lot slower, in my time doing stuff. 

Especially if there is a folders for all models related to a set of models 
for example a wooden set of furniture, plastic set, metal set and so on, 
but you just want to grab all the chairs, not worrying about sets, if i want the sets, i can just search "metal" and they are all there (i name things like that it makes most sense.)

Dealing with folders in that case is really horrible, and it would make one just want to throw everything into the root folder and not deal with them issues. That's the reason why a folder view VS flattened hierarchy is nasty for artists to deal with usually.
