### ISSUE TITLE
Reimplement info_offscreen_movie_texture and VR monitor 

### ISSUE THREAD

**Issue by SnoByte** [sboxgame/issues#2023]
### For?

S&Box, Hammer

### What can't you do?

Can't play webm video's in-game as a material on a mesh using info_offscreen_movie_texture entity and the VR_Monitor Shader

### How would you like it to work?

Implementation of a new C# entity similar to "info_offscreen_movie_texture" and a new shader similar to the VR Monitor shader from HL:A 

### What have you tried?

No workaround.

**Comment by handsomematt** [comment]
We'll implement video decoding #993 - what does the VR Monitor Shader look like / do

**Comment by Adesii** [comment]
iirc info_offscreen_movie_texture is just a way to play panorama videos onto a Monitor remotely.
so basically instead of having the monitor and the video player onto the same entity they are separated so you can play multiple videos on the Monitor in sequence.
This is what is used in the Intro of HLA with the Video call.

The monitor shader itself is just a render target and im pretty sure already exists due to the Sceneportal stuff.

**Comment by xezno** [comment]
You can play videos now, and I think there are shaders on asset.party that match the VR monitor shader (at least based on your description).
