### ISSUE TITLE
Can't submit leaderboard score using float values- currently integer only.

### ISSUE THREAD

**Issue by ShadowBrian** [sboxgame/issues#2297]
### What it is?

Can't submit leaderboard score using float values- currently integer only.
To clarify this is with the new leaderboard API.

### What should it be?

Should be able to submit float values, my current use is sending a completion time for my maze game, if I sent milliseconds as an integer or something instead of just seconds as a float it'd probably run into int.max at some point, does not seem like a nice solution.

**Comment by Metapyziks** [comment]
Milliseconds should be safe, since the max integer is ~2 billion. That'd mean the biggest supported time would be over 12 days. Since the tickrate is something like 60hz, you may as well only store down to hundredths of a second, giving you 120 days to work with.

Despite that, I can imagine floats being useful still, so I'll add extension methods to submit / read them.

**Comment by ShadowBrian** [comment]
Thanks for the perspective, will get milliseconds up in my game for now then, should be ok theoretically...

**Comment by tjones4701** [comment]
The steam leaderboard doesn't support floats. I think the solution was to convert it instead to an int.

Maybe they could add support into the leaderboards functions to automatically do this for us?

**Comment by garrynewman** [comment]
Yeah we probably should support float somehow
