### ISSUE TITLE
Texture.Create throwing nonsense render target error

### ISSUE THREAD

**Issue by rileyzzz** [sboxgame/issues#2392]
### Describe the bug

When I create a procedural texture using Texture.Create and DXT5 as the format, I get this in the console:
`Trying to create a render target with invalid image format DXT5`

My code is literally just this:
```
Texture.Create( Width, Height, ImageFormat.DXT5 )
					.WithMips( MipMaps.Length )
					.WithStaticUsage()
					.WithData( GetAllMipData(0, 0) )
					.Finish();
```

### To Reproduce

Create a 2d texture with DXT5 or DXT1 as the format.

### Expected behavior

The texture should be created correctly without an error.

### Additional context

This code was working correctly ~1 month ago - possibly a result of the new RenderHook stuff?

**Comment by robotboy655** [comment]
This happens because if you have mipmap count above 1, the engine will try to auto generate mipmaps for you, which requires the texture to be a render target, which can't be DXT5. Your mipmap count is what has changed for you I imagine.

I will make it not try to generate mipmaps for static textures that provide mipmap data like in your scenario. Let me know how that goes.

**Comment by rileyzzz** [comment]
@robotboy655 Seems to be working again for DXT1 and DXT5 2d textures, though it seems like i'm still getting the problem with procedural cubemaps.  It doesn't throw any render target error now, but DXT1/DXT5 cubemap data that was working fine a few weeks ago is now giving me the purple and black checkered texture when i try to use it on a material. The cubemaps aren't using any mips at all (iirc ognik said the engine doesn't support them on cubemaps), so the data I upload for those has always just been for the first mip.

**Comment by ogniK5377** [comment]
Cubemap mips were fixed, could be something else going on
