### ISSUE TITLE
`Predicted` doesn't work on Components set using `BindComponent`

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2624]
### Describe the bug

When components are set using `BindComponent`, you're unable to mark them as 'Predicted', as they're missing a setter.

This means any properties on that component also cannot be marked predicted and will not be treated as such.

### To Reproduce

1. Create a component using the `BindComponent` attribute
2. Mark a property on it as predicted
3. See that it does not get predicted.

### Expected behavior

`Predicted` attribute works, either automatically or manually.

### Additional context

Components need some love. 😔 
Lemme know if you want me to upload a repro

**Comment by LeQuackers** [comment]
Actually I looked into this when I was trying to use components to add predicted/simulated behavior to pawns dynamically (related to #2591). Essentially all components are *not* predicted/simulated, but the container that holds them (the `NetworkComponents` property form `Entity`) is.

**Comment by Fortune117** [comment]
Interesting. There's gotta be a better way of making this stuff obvious to the user, I was using prediction reliant code in components for ages before realizing that was the root of a tonne of my issues.

**Comment by LeQuackers** [comment]
I wrote a proof of concept "pawn proxy" which is an entity that wraps around an existing pawn that allows you to add `[Net, Predicted]` properties and a custom `Simulate` method dynamically; I made a test addon called "Double Jump" for the default sandbox gamemode that added a predicted/simulated extra jump to the player, but it's not really practical because it breaks when `Client.Pawn` is casted. If the "pawn proxy" inherited form the gamemode's `Pawn`/`Player` class instead of `Entity` it would probably work better, but programming a specific solution for every gamemode sucks.

I'll go ahead and make the "Double Jump" addon public again so it can be used in sandbox, but keep in mind it's still a PoC/WIP and barely working. If you press your use key on the box entity spawned from the addon you'll get a double jump, but your `Pawn`/`Player` will be broken.

I'll upload the source for it in the morning.

**Comment by LeQuackers** [comment]
The addon is public again so it can be used in the sandbox gamemode.

Here's the [repo](https://github.com/LeQuackers/double_jump).

**Comment by LeQuackers** [comment]
Components not supporting prediction/simulation will break [`WeaponComponents`](https://github.com/DevulTj/sbox-template.fps/tree/template/code/Systems/Weapon/Components) from the [fps template](https://github.com/DevulTj/sbox-template.fps) in the works; adding support for this before the template is finished/released should be considered.

**Comment by Fortune117** [comment]
added by conna <3
