### ISSUE TITLE
TransmitType.Whitelist

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2813]
### For?

S&Box

### What can't you do?

Currently you're unable to manually select which clients an entity should be replicated to.
I'm proposing a new `TransmitType` named either  `Whitelist` or `Manual` which will allow for such functionality.

### How would you like it to work?

`TransmitFilter` or `ReplicationFilter` container property that contains the whitelisted clients. The entity will be replicated to these clients when `TransmitType` is set to `Whitelist`.

### What have you tried?

No workarounds currently! You could use a ClientRPC to share some private data with a certain client but that's about all we have right now.

**Comment by LeQuackers** [comment]
Wouldn't #2108 fit the bill?

`TransmitFilter`/`ReplicationFilter` could work, but I think leveraging tags would add a lot of flexibility ([WIP example](https://github.com/sboxgame/issues/issues/2108#issuecomment-1328098219)).

**Comment by Weldify** [comment]
I feel like tags aren't the best solution to this. Imagine you have a loot bag entity and you want to transmit it to certain clients within a radius. With this you could easily select the clients based on their distance every tick. With tags, you would have to make a specific tag for this specific bag and then also assign that tag to clients, which also makes you  responsible for removing it later.

In this case tags are limiting.

**Comment by LeQuackers** [comment]
That's a good point, but I feel that tag-based networking would still have a lot of use.

What about in the case of instances? Lets say lots of clients are in the same area, but only groups of 4 share a common instance that allows them to interact with each other without disturbing the other instances; in that case tags would be a better choice because the instance, collisions/traces, and (maybe) sounds could be controlled by a single tag. If a `TransmitFilter`/`ReplicationFilter` was used, it'd have just as much overhead as the example you gave about tags.

If we had a loot bag entity in an instance that should only be networked to clients in a certain radius that are also in the same instance as the bag, then that would cause problems for both `TransmitFilter`/`ReplicationFilter` and tag-based networking.

I suppose both could be added; the idea with tag-based networking was to gather applicable clients based on the entity's `TransmitType` and then filter the clients further based on what "generic tags" each client did/didn't have compared to the entity's own "network tags", so a `TransmitType.Whitelist`/`TransmitType.Manual` should work with it.

**Comment by Weldify** [comment]
You'd be able to easily hook `ReplicationFilter` to tags though. Not the other way around though

**Comment by mattkrins** [comment]
Agreed @Weldify
This is exactly what we need. Until this is implemented, any large scale projects are essentially nonviable.

**Comment by LeQuackers** [comment]
I gave it some more thought and one thing that might still be a problem is figuring out which clients are in a given entity's PVS; using the instance example again, if the area was large enough we wouldn't want every entity in the instance constantly transmitting, so having something like `Game.GetClientsInPVS(Entity entity)` would really complement `TransmitFilter`/`ReplicationFilter`.

**Comment by lotuspar** [comment]
Bumping this - this is pretty crucial for the game I'm working on.

It's just generally important too... has a dev seen this yet?

**Comment by mattkrins** [comment]
> has a dev seen this yet?

Not as far as I am aware.
I'm in the same boat.

**Comment by Weldify** [comment]
I know that this didn't have any activity in a long time, but I came up with a better idea: just scrap TransmitType. Instead of it, add `virtual ShouldTransmit(IClient cl)` to entities. By default it should transmit everything in pvs. `IClient` should get extension methods for pvs too.

Examples:
dont transmit to anyone:
`override ShouldTransmit(IClient cl) => false`

only transmit in PVS:
`override ShouldTransmit(IClient cl) => cl.PvsContains(Position)`

This system will be a lot more flexible.

**Comment by trende2001** [comment]
This needs to be a must-have

**Comment by mattkrins** [comment]
I have no clue how this will look after the [retooling](https://sbox.facepunch.com/news/retooling/) since I assume entities will behave very differently to how they do currently.
