### ISSUE TITLE
Inspector slider for int properties doesn't work properly

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2909]
### Describe the bug

Attempting to use the mouse slider for int properties in asset or entity inspectors results in some weird behavior.

### To Reproduce

1. Make a GameResource with an int property or inspect an entity with an int property and try to edit it using the mouse slider by clicking and holding on the left most icon of the input field.
2. Notice weird behavior that seems tied to velocity and is hardly usable to actually edit the value.

### Expected behavior

It should work based on the distance, float properties seem to work fine, this issue only applies to int types.

### Media/Files

![sbox-dev_O7uh6gLtol](https://user-images.githubusercontent.com/12602100/218829695-8f35cb7c-8f32-40c3-8a4b-2fb407f23c6f.gif)

**Comment by robotboy655** [comment]
I have reworked Int/FloatProperty drag value change system

Works much better for ints now, faster value change when further vertically from the slider (rather than changing speed from top of the screen)

Let me know what you think. We could switch to holding shift/ctrl/alt for speeding up/slowing down the drags. The original system also did change speed the further away you are from the top of the screen, which I thought was a weird way to do it.

**Comment by Willco2** [comment]
Sliding the value like that doesn't actually change the value of the property, until a different property is modified or the resource is saved. I looked at the IntProperty code, and adding `SignalValuesChanged();` near the end of the file, similar to FloatProperty, seemed to fix it.

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by DoctorGurke** [comment]
This seems to work nicely, thank you
