### ISSUE TITLE
Possibly issue with custom surface properties, not sure.

### ISSUE THREAD

**Issue by kodi022** [sboxgame/issues#2916]
### Describe the bug

I have a model with one shape being a custom surface property. This shape does not get set to the correct coordinate of the model, and so is just near 0,0 by its base offset. I dont know exactly why its happening, but its reproduced so hopefully something can be figured out.

The physics shape goes to the correct location if you hit the recompile button on the model ingame.
But breaks if you reload the game.

Bug Applies to Editor and normal game.

### To Reproduce

1. make model with some physics shapes, one being a custom surface property
2. spawn entity with model not at 0,0
3. go to 0,0 with wire on (under spawn if flatgrass)
4. witness the orphaned physics shape

### Expected behavior

it should be with the model like the other physics shapes

### Media/Files

here is a base gamemode with the bug exampled
[model_bug_test.zip](https://github.com/sboxgame/issues/files/10748037/model_bug_test.zip)

In-game with server wire on: 
![sbox-dev_TRfIvhT2tA](https://user-images.githubusercontent.com/29390269/219174069-ad1780ae-9af3-41d9-937d-940aa5c53b28.png)

In-game at spawn with server wire on: 
![sbox-dev_dxHaT1ucZp](https://user-images.githubusercontent.com/29390269/219174008-c8477491-c21e-425f-91fa-8f2ed3ec7f44.png)

Modeldoc of the model: 
![sbox-dev_inE2e0B5OO](https://user-images.githubusercontent.com/29390269/219174247-42b4f347-1eaa-43c1-98fa-c6e2c64a4569.png)

### Additional context

please ping me in the discord how/when this is fixed, its been holding back my games next update, and id like to continue with it asap.

**Comment by robotboy655** [comment]
As far as I can tell the problem is a combination of issues:
1) ModelEntity.Position does not move the other PhysicsBodies which is why the physics body for the button stays below ground, where you initially spawned the model
2) Your model does not attach the button's physics body to the rest of the model
3) You are spawning the model with static physics, which appears to not support physics body joints (i.e. making secondary physics bodies move with main one via physics), you probably want keyframed physics if you want to make that button move and stuff.

Regarding fixing this, I will look into making ModelEntity properties move all the bodies for you.

**Comment by robotboy655** [comment]
ModelEntity.Position and similar properties now move all physics objects, so it should work correctly now.
