### ISSUE TITLE
Option to change compiled texture format to reduce filesize

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2929]
### For?

S&Box, Material Editor

### What can't you do?

I'm unable to specify the compression format for compiled textures, specifically color maps, as they use BC7 by default. This results in unnecessarily large filesizes.

While BC7 is very good for textures which have to be as close to the uncompressed texture such as normal maps, for most color maps there is virtually no perceptible difference between BC1 and BC7. It should be up to the user to decide which one to use. It also looks like VTEX already supports BC1 (and a bunch of other formats), so my guess is this would be pretty much just an option in the texture settings.

### How would you like it to work?

Specify the compression format in the Texture Settings.

### What have you tried?

Crying.

**Comment by handsomematt** [comment]
Shaders define output format with OutputFormat.

Letting artists define this would be complicated to implement and nearly all the time cause worse results from people who think BC7 is good for normal maps instead of BC5.

The BC compressed textures go through a file compression after, you can make this compression more effective by reducing the entropy of your input files by not using .jpg source textures.

**Comment by Gmod4phun** [comment]
Input filetype is irrelevant in this case. The issue is the bit depth of the compiled texture. Being able to change the bit depth of the compressed textures should be a thing, like it is in pretty much all game engines as far as I am aware. I don't see how this would cause worse results or be complicated to implement.

Sorry if I sound like a dick, that is not the intention really, I just seriously don't understand why changing the way a texture is compressed is such an issue.

**Comment by Gmod4phun** [comment]
One more thing I noticed is that the complex shader spits out a BC7 color texture if a metalness texture is used, whereas it spits out DXT1 (BC1) if metalness texture is not used. Using a metalness texture should not affect the color texture's format.

**Comment by handsomematt** [comment]
It packs the metalness texture into the alpha channel using BC7, otherwise it uses BC1.

It already does what is best.

**Comment by NotGaylien** [comment]
I think that this probably is a bit of a bad idea.

because different shaders will have different texture inputs that are packed in different ways,
like 1 shader could pack metal, roughness, ao, alpha into the RGBA of a single texture in which case you might want BC7 so they all end up nice.
and it might pack normals XY into the RG of a texture and nothing to put into the extra channels, so would want BC5 or whatever.

allowing people to fuck with that is a awful idea imo, i get you want to reduce file sizes or have more control over the compression.

but whoever made the shader would have set what format it should be because thats what is best and what it should be using in its use case, unless the person who made the shader did alot of fucked stuff, in which case, the shader itself probably isnt optimised well as a whole then, so you should worry about the shader as a whole and not the texture format.

**Comment by Gmod4phun** [comment]
Unless my observations are wrong, using a 512x512 color texture with a 4K metalness texture results in the 512x512 color texture being resized to match the metalness, saves the result as BC7 and produces a 18MB compiled texture.

A 512x512 BC1 texture is 128KB and a 4K BC1 texture is 8MB. That's less than half of the original size, and that is just one texture set for a single material. Same thing goes for roughness being stored in the normal map's alpha.

Who would use a 512 colormap with a 4K metalness texture you ask? That is a more extreme example, but that's just to show one part of the problem (textures being upsampled to match the biggest texture).

If it's faster for the shader to just access fewer compiled textures (color+metal and normal+rough) rather than having them each as a standalone texture, then I kinda get the reasoning, but it still results in alot of unnecessary space wasted by textures which could be otherwise smaller.

I guess this will not be changed anytime soon, if ever, but I still think it would be helpful to have the option at some point.

**Comment by SirYodaJedi** [comment]
Being able to use BC7 instead of DXT1 when there is no alpha channel would be very useful for high-detail, lower-resolution textures (ex: 128x128, 256x256). Yes, you can select "no compress hint", but that makes the texture RGBA8888; why waste space with a 32-bit format when an 8-bit format works great?

**Comment by handsomematt** [comment]
That is already what happens automatically.

**Comment by SirYodaJedi** [comment]
> Being able to use BC7 instead of DXT1 when there is no alpha channel would be very useful for high-detail, lower-resolution textures.

Or not necessarily low-resolution, but low-texel density. Example:

| Uncompressed	| DXT1	| BC7 	|
|--------------	|--------	|---------	|
| ![+0MEDKIT_orig](https://github.com/sboxgame/issues/assets/50331474/3ad2b5a8-d578-4e2b-957f-cf8503510985)	|  ![+0MEDKIT_dxt1](https://github.com/sboxgame/issues/assets/50331474/b9f3139c-b76c-4c11-b4a0-34ec36d51c41)	|  ![+0MEDKIT_bc7](https://github.com/sboxgame/issues/assets/50331474/e975dde2-b5fc-4598-883f-89e40475770f)	|
