### ISSUE TITLE
[Shader Graph] Option to bake out textures

### ISSUE THREAD

**Issue by DeltaDesigns** [sboxgame/issues#2992]
### For?

Other

### What can't you do?

I don't know how many people would use it but being able to make a shader then being able to bake out the textures for diffuse, metal, rough, etc which would allow the user to use the textures in the complex shader instead or somewhere else outside of s&box or just for performance reasons

### How would you like it to work?

N/A

### What have you tried?

N/A

**Comment by PixelQubed** [comment]
This would not be too useful since shaders are not for making textures themselves in games. Yes, they are a part of creating textures since, without shaders, we wouldn't have any way to communicate with the GPU. We have programs to make textures, such as Substance Designer and Quixel Mixer, which is free, plus you have Megascans too. Shaders are more of an accommodation or compliment to textures, in my opinion. If you are after making something static, there is no point in making a shader to do that one thing since it's a waste of resources.

**Comment by aylaylay** [comment]
Yeah I agree, there's tools for texture creation, I don't like the idea of using shadergraph to generate textures.
