### ISSUE TITLE
A way for Addons to inject animations into Animgraphs.

### ISSUE THREAD

**Issue by badandbest** [sboxgame/issues#2997]
### For?

S&Box, Other

### What can't you do?

If I'm making a gamemode and want to add a new animation to my player, I'd just add the sequences and add it to the animgraph.

But if I'm making an addon for a game and wanted to add, say, a new player hold type animation for my custom weapon, I'm out of luck.

### How would you like it to work?

We've been discussing ideas in the #animgraph channel. Adesi suggested an inject node which lets you name it and then use Model.SetInjectAnimation("name",animresource);

Going back to the hold type animation, you would need an aim matrix + weapon animations etc for that too. Would it be possible to inject an entire graph? I don't know.

### What have you tried?

<details>
<br>
<summary>What I've tried (Taken from my reply)</summary>
In this example gamemode I have a player character with Idle and Pistol animations.

![image](https://user-images.githubusercontent.com/91832803/224512489-bdf1063a-a182-4324-8d27-84a48fbe6e83.png)

![image](https://user-images.githubusercontent.com/91832803/224512590-4f4b760b-12d2-4d9a-b308-92a19fc7cd5f.png)

Then in my shotgun addon I use the original player model as a base to then add shotgun animations.
![image](https://user-images.githubusercontent.com/91832803/224512539-b1e3f486-e3e9-4b09-bb8c-8d08b957b9c7.png)
![image](https://user-images.githubusercontent.com/91832803/224513129-a936d679-f7f6-4c28-b0c3-e07a638863ca.png)
![image](https://user-images.githubusercontent.com/91832803/224512942-aa97cdea-866b-46fe-8b1e-70d6824ce13d.png)

But obviously the base character isn't going to have these animations or the new animgraph. So when I equip the shotgun I need to replace the model with the one from the addon.
![image](https://user-images.githubusercontent.com/91832803/224513000-02bdd2c5-6e50-40d3-9c46-50d651e102b6.png)

Because of this, addons that use this method don't blend their new animations for obvious reasons.

https://user-images.githubusercontent.com/91832803/224515677-336414f5-1a20-4445-aa9c-7db9e063eb70.mp4

Why not replace the model when spawning? Yes, that would fix the blending for the weapon addon, but using multiple weapon addons would allow only one of them to replace the model.

![image](https://user-images.githubusercontent.com/91832803/224513184-986e6fc7-640e-4c68-9fd9-5f0e30e33754.png)
</details>

### Additional context
Here are the files for the gamemode and two weapon addons for anyone wanting to take a look.
[gamemodes and addons.zip](https://github.com/sboxgame/issues/files/10949659/gamemodes.and.addons.zip)

**Comment by robotboy655** [comment]
Correct me if I am wrong, but isn't this is what the following option is mean to help with?
![image](https://user-images.githubusercontent.com/3299036/224374636-aa1cad90-4403-4cfb-96c1-c267044debf1.png)

Should allow you to add animations and what not to the base model.

For anim graphs, I think the subgraphs feature will help you achieve what you want.

Perhaps someone more familiar with these features should write up a guide on wiki about it.

**Comment by yourbadandimbest** [comment]
@robotboy655 
> Correct me if I am wrong, but isn't this is what the following option is mean to help with? https://user-images.githubusercontent.com/3299036/224374636-aa1cad90-4403-4cfb-96c1-c267044debf1.png
> 
> Should allow you have a custom model that has everything from the base model + any custom animations and what not that you may want.
> 
> For anim graphs, I think the subgraphs feature will help you achieve what you want.
> 
> Perhaps someone more familiar with these features should write up a guide on wiki about it.

I have actually tried this.
![image](https://user-images.githubusercontent.com/91832803/224512457-f52d765b-72a7-4021-89ae-b3759195bcf4.png)

In this example gamemode I have a player character with Idle and Pistol animations.
![image](https://user-images.githubusercontent.com/91832803/224512489-bdf1063a-a182-4324-8d27-84a48fbe6e83.png)
![image](https://user-images.githubusercontent.com/91832803/224512590-4f4b760b-12d2-4d9a-b308-92a19fc7cd5f.png)

Then in my shotgun addon I use the original player model as a base to then add shotgun animations.
![image](https://user-images.githubusercontent.com/91832803/224512539-b1e3f486-e3e9-4b09-bb8c-8d08b957b9c7.png)
![image](https://user-images.githubusercontent.com/91832803/224513129-a936d679-f7f6-4c28-b0c3-e07a638863ca.png)
![image](https://user-images.githubusercontent.com/91832803/224512942-aa97cdea-866b-46fe-8b1e-70d6824ce13d.png)

But obviously the base character isn't going to have these animations or the new animgraph. So when I equip the shotgun I need to replace the model with the one from the addon.
![image](https://user-images.githubusercontent.com/91832803/224513000-02bdd2c5-6e50-40d3-9c46-50d651e102b6.png)

Because of this, addons that use this method don't blend their new animations for obvious reasons.

https://user-images.githubusercontent.com/91832803/224515677-336414f5-1a20-4445-aa9c-7db9e063eb70.mp4

Why not replace the model when spawning? Yes, that would fix the blending for the weapon addon, but using multiple weapon addons would allow only one of them to replace the model.

![image](https://user-images.githubusercontent.com/91832803/224513184-986e6fc7-640e-4c68-9fd9-5f0e30e33754.png)

I hope you see the problem.

Here's the files for the gamemode and the two weapon addons if you want to take a look.
[gamemodes and addons.zip](https://github.com/sboxgame/issues/files/10949659/gamemodes.and.addons.zip)
