### ISSUE TITLE
Addons that are included in the map don't get automatically downloaded

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#3133]
### Describe the bug

Hammer entities that were downloaded from a map addon don't get automatically downloaded for everyone else that plays on the map. They only start working when you include them in the addons list of the server. So every time you want a certain entity in your map to work, you have to ask the server host to find it in a giant list and include it in the server itself.

### To Reproduce

1. Install a map addon (presumably Jump Pad for example)
2. Put it in your map and compile your map
3. Create a lobby (on any gamemode, preferably Sandbox)
4. Don't manually add the addon in the addons list of the lobby
5. Launch the server, then the console will complain that there's an unknown entity

### Expected behavior

It should automatically download addon entities like it used to. No manual interference should be required

**Comment by garrynewman** [comment]
I'm gonna do this today @handsomematt

**Comment by trende2001** [comment]
Also, newer map addons don't show up here anymore
![image](https://user-images.githubusercontent.com/68961063/231961446-38f6a6e6-1937-45ec-9e14-f7dc437b0fc9.png)

**Comment by garrynewman** [comment]
What's your addon name? Where is that popup from?

**Comment by trende2001** [comment]
https://asset.party/trend/pixelscreen
This is the menu that pops up when you click Add Addon in the hammer entity tool bar

**Comment by trende2001** [comment]
> [asset.party/trend/pixelscreen](https://asset.party/trend/pixelscreen) This is the menu that pops up when you click Add Addon in the hammer entity tool bar
> 
> For other people to install my addon now, they have to do `package_install trend.pixelscreen` Although, sometimes it doesn't even pop up in the entity list after installing it

Nevermind, I had to add tags in asset.party that are "map" and "entity". The issue about them not downloading isn't solved yet though

**Comment by chrisspieler** [comment]
Issue still persists. There's a gamemode and map on asset.party that can be used to repro this issue.

Repro:
Start a new game of "duccbox" (duccsoft.super_ducc_test)

Expected Result:
The Sandbox mode toolbar and health are invisible because a map entity from an addon ran a command to disable the hud. This addon was specified by the map metadata like so:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/8889285/232880207-a3258127-9332-4a77-a799-48e6aa439433.png">

Actual Result:
The HUD is still visible, and we get the following errors and package_list output:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/8889285/232880493-a1afe02b-1258-460f-9d20-686cce4323cd.png">

Workaround:
Run `package_install duccsoft.command_entities server` before launching the duccbox gamemode.

**Comment by sugmagaming** [comment]
can someone please fix this issue? there is a map im making that is finished but this needs to be working for it to work properly :(

**Comment by garrynewman** [comment]
Should work now, you'll have to open your map and save it once, then on re-upload it should have references visible in the version.

**Comment by trende2001** [comment]
Thank you so much, it's working now
