### ISSUE TITLE
Multiple asset browsers

### ISSUE THREAD

**Issue by drednorzt** [sboxgame/issues#3183]
### For?

S&Box

### What can't you do?

Have multiple asset browser windows open (even just two would be fine).

### How would you like it to work?

Something quick to access, like a button in one of the Asset Browser dropdown menus that just says "Duplicate window", "Second Browser" or similar

### What have you tried?

Tried using the legacy asset browser at the same time, but using two different interfaces for the same thing doesn't make it any easier.

### Additional context

When I'm setting up new models, I'm frequently having to move back & forth in the Asset Browser between my material & model sub-directories. It would be a huge QoL improvement to have more than one asset browser open at the same time

**Comment by xezno** [comment]
Hey, this should be fixed on next update. You can add a new asset browser through the View menu:
![image](https://github.com/sboxgame/issues/assets/12881812/0b3843b0-0684-4de2-b628-f3d2474201ac)
These will persist between sessions, they'll save whatever you were looking at.

You can also drag files around now - between asset browsers, within the same asset browser, and from the OS file explorer. If you want to make a copy of a file instead of moving it, hold control (same control scheme as Windows).
