### ISSUE TITLE
UI: Flex panel children aren't displayed normally but correctly when console is open 

### ISSUE THREAD

**Issue by websaid** [sboxgame/issues#323]
**Describe the bug**
A Panel with `display: flex;` and `flex-direction: row;` is being displayed wrong, not all children are displayed properly, its parent element has a width of 1200px:

![image](https://user-images.githubusercontent.com/58175915/121261182-ab621d80-c8b2-11eb-82a1-44b0beff2fa6.png)

But when looking at the scoreboard through the console it's displayed correctly:

![image](https://user-images.githubusercontent.com/58175915/121262556-a4d4a580-c8b4-11eb-8419-2dced2b9ad16.png)

This panel contains four Labels, the first with `flex-grow: 1;` and the last three with `width: 90px; text-align: center;`. 
We noticed that changing this width will effect the proper visibility of these flex elements. 

Also this Panel is displayed differently on other screen resolutions:

![image](https://user-images.githubusercontent.com/58175915/121263443-e7e34880-c8b5-11eb-806f-5404b8ade8d8.png)

Still correct if the console is open:

![image](https://user-images.githubusercontent.com/58175915/121263558-0f3a1580-c8b6-11eb-9d77-08ec253a3a8d.png)

**To Reproduce**

1. Clone branch "hud-flex-bug-issue":  https://github.com/TTTReborn/ttt-reborn/tree/hud-flex-bug-issue
2. Load the gamemode and open the scoreboard 

**Expected behavior**

To be correctly displayed like when the console is open or like the web version of our UI on http://ttt-sbox.com/

**Additional context**

Screen resolution on the first screenshots: 2560x1440
Second screen: 1920x1200

**Comment by garrynewman** [comment]
Does it maybe work if you do `flex-shrink: 0` on .core/karma/ping?

**Comment by Westsaid** [comment]
@garrynewman  No this has no effect unfortunately... 
![image](https://user-images.githubusercontent.com/58175915/121311856-19cfcb80-c905-11eb-9e8a-7d9177b17397.png)

**Comment by Alf21** [comment]
Checked again today, and this issue does not appear to me. It's definitely caused by the screen resolution, as @Westsaid still has this issue (and he isn't alone).

![image](https://user-images.githubusercontent.com/11843790/128084818-a1f8a4b3-e16e-4454-972f-b701d66ebec7.png)

After testing my current UI stuff, Westsaid experienced another bug:

https://user-images.githubusercontent.com/11843790/128084883-6b7a2fe5-4ea7-4e91-a4ce-8bf5c6e3856e.mp4

Could be caused by myself (as I worked in that PR with the matrix transforms Garry suggested), but this issue doesn't happen to me. So maybe (!), could it be that just the Matrix isn't calculated in the right way if you do not have an (ultra-)wide screen?

How it should work:

https://user-images.githubusercontent.com/11843790/127726830-ec19bbc7-a737-41a4-9969-92b86ca3a169.mp4
