### ISSUE TITLE
`Long Brown Test` hair allows for multiple hairstyles

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#3293]
### Describe the bug

You can wear the hairstyle `Long Brown Test` with any other hairstyle, this causes issues in game modes that use a clothing container to replace the headpiece since it doesn't get removed.

### To Reproduce

1. Go to the avatar selection and find `Long Brown Test`
2. Wear it with any other hairstyle

### Expected behavior

Only one hairstyle, or set up `Long Brown Test` with the same properties as other hair.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/32153021/e100e891-f024-43eb-af38-55e0a1cc51d3)

### Additional context

Might be already known by the artists, I'll close this if I see it removed at some point.

**Comment by DevulTj** [comment]
I fixed the slot configuration for this hair type, but I'll keep this issue open and refer to @DanduwFP regarding the name of the clothing item.

**Comment by DanduwFP** [comment]
This asset 'Long Hair Test' was made so we could try and get the hair to work with the hats, since in the modeldoc we have multiple versions of the hair, which *should* be change-able when selecting different hats. We just haven't sorted it out yet. Or no one's jumped onto implementing this. I can see if I can get some some to look into this because at the moment it's been left as a test asset.

**Comment by DanduwFP** [comment]
So i'd say, mind the issues with it, since it's generally a test asset we're trying to get sorted so it can interact with the hats correctly.

**Comment by matekdev** [comment]
Sounds good, closing,
