### ISSUE TITLE
Labels can no longer have children

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#3339]
### Describe the bug

Labels can no longer have children and just throw an exception when attempting to add a child to a label Panel.

### To Reproduce

1. Try to add a child to a label panel.
2. See exception

### Expected behavior

This was a recent and seemingly arbitrary change. I'm not sure if we're supposed to update all of our UI now or if this was an accidental/temporary change.

### Media/Files

![sbox-dev_UZvB71PVw8](https://github.com/sboxgame/issues/assets/12602100/657c0605-6f9d-44a4-820b-e80f32bab0d9)

### Additional context

We're using child labels in multiple places for some procedural effects like seen in the video. (Video taken before aforementioned update) It would be a shame if we had to go back to a bunch of past projects and wrap single labels in dummy panels just so we can still do this effect.

https://github.com/sboxgame/issues/assets/12602100/fe1b2e83-d050-4bdb-a298-958447a1255a

**Comment by garrynewman** [comment]
What's the expected behaviour of a label with a child? Does the child go before or after the content?

**Comment by DoctorGurke** [comment]
Well what was the behavior for the past two years? I'm not really too sure about the implications under the hood

**Comment by DoctorGurke** [comment]
judging from the video though they seem to just go after?

**Comment by trundlr** [comment]
I don't know how the behaviour should work either, but it's a very common pattern in frontend work to use a \<p> or \<label> tag, and then dispersed within the text might be \<span> tags so you can change the style of one particular word.

```html
<label>Welcome to my <span class="bold upper">awesome</span> site!</label>
```

**Comment by garrynewman** [comment]
But would you do 

```
var label = new Label ( "Welcome to my");
var span = new Label (){ Element = "span", Classes = "bold upper", Text = "awesome", Parent = label );
```

**Comment by matekdev** [comment]
> But would you do
> 
> ```
> var label = new Label ( "Welcome to my");
> var span = new Label (){ Element = "span", Classes = "bold upper", Text = "awesome", Parent = label );
> ```

I guess this works but it would be nice to have an HTML equivalent for this as well. Like, Razor is really neat and I practically never have to create UI elements in C# code anymore, would be a bit annoying if I had to for this use case.

**Comment by garrynewman** [comment]
But you can just use span, or Panel instead of label and put your children inside that

**Comment by DoctorGurke** [comment]
At this point I'm only really asking what was wrong with the old behaviour and why it was changed. If you think this restriction should stay then it should be communicated that we have to update our games accordingly instead of waiting with broken UI for a fix that might never come.
We're trying to get a wiseguys update ready soon and parts of the UI are currently completely broken after this update

**Comment by trundlr** [comment]
> But you can just use span, or Panel instead of label and put your children inside that

What if we want to utilize styles defined for label from a parent? It really breaks down the flow when label has different behaviour than any other built-in component. 
I assume the change was due to how child content is added to panels in general. In my opinion, the "magic" that goes on behind the scenes should not interfere with how we write something as simple as a <label> tag. Perhaps we could retain the label tag for its previous use, and an entirely different tag (that we as developers are not meant to use) can handle the specific childing behaviour. 

If not, it's really not a big deal. It is straightforward to work around. But I think it will be confusing for new developers if you leave it how it is.

**Comment by matekdev** [comment]
When using an existing language, framework, etc. I feel like to cause the least amount of developer friction is to ensure it behaves the exact same. Whether it's arbitrary rules in HTML, CSS stylings that behave differently, or CSS stylings that aren't implemented, none of this should ideally exist in s&box.

> At this point I'm only really asking what was wrong with the old behaviour and why it was changed. If you think this restriction should stay then it should be communicated that we have to update our games accordingly instead of waiting with broken UI for a fix that might never come. We're trying to get a wiseguys update ready soon and parts of the UI are currently completely broken after this update

Also, please don't be dissuaded from continuing to make changes that break people's games. s&box is waaay too earlier in its lifecycle to be concerned about this.

**Comment by garrynewman** [comment]
> At this point I'm only really asking what was wrong with the old behaviour and why it was changed. If you think this restriction should stay then it should be communicated that we have to update our games accordingly instead of waiting with broken UI for a fix that might never come. We're trying to get a wiseguys update ready soon and parts of the UI are currently completely broken after this update

That's fair. The reason it was changed was because to get around this restriction every label had another label inside them.. which if you have 1000 labels, adds 1000 more labels to tick. On balance, this is the same behaviour as an image.. you don't try to stick new panels inside an <img> or a <video>.

So I think the move here is going to be to treat <label> like a <text> in blazor - and not parse html inside of them. If you try to manually add a child, we should add it as the next sibling.

**Comment by trende2001** [comment]
Does that mean all of our games are broken now or is the commit going to get reverted

**Comment by garrynewman** [comment]
It won't get reverted, but I'll change the behaviour so it adds it as a sibling instead
