### ISSUE TITLE
A way to disable lag compensation temporarily

### ISSUE THREAD

**Issue by Igrium** [sboxgame/issues#3575]
### For?

S&Box

### What can't you do?

I'm writing weapon shooting code, and for [reasons too complex to get into](https://github.com/Igrium/clock_blockers/blob/master/notes/weapon_pseudocode.md), I need to obtain the non-lag-compensated position of an entity in a lag-compensated context (server-side, of course).

### How would you like it to work?

Kind of like with prediction, it would would be nice to have a way to turn off lag compensation temporarily like:

```cs
using ( LagCompensation.Off() ) 
{
    // Do random shit...
}
```

### What have you tried?

The only other solution I can think of is to add a component to each entity that backs up its position each tick before we enter the lag-compensated context. This is bad for obvious reason.

I could also try saving the position of all the entities before entering the lag-compensated context, but this is also bad.

**Comment by handsomematt** [comment]
This is daft sorry, you would be rewinding everything back to its original position, then rewinding again and again...

**Comment by Igrium** [comment]
So what would you say is the best way to do this?

**Comment by Weldify** [comment]
I feel like this should get a second thought. Its useful for me because ive got a bunch of components that i simulate and most of them need lag compensation, so i turn it on, but one of them doesnt, so pausing compensation during it would make the most sense, because if i dont do that then ill have to go through and compensate everything separately but thats fuckin stupid,
