### ISSUE TITLE
Let us pass components through ConCommands

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3656]
### For?

S&Box

### What can't you do?

Currently I'm unable to pass entity components through console commands.

### How would you like it to work?

You should be able to pass a component through a console command.
Would also be nice if components implemented `IValid` to make checking them easier

### What have you tried?

Using a common base class for components that need to be passed through console commands that assigns them unique ID's and lets me find them that way

**Comment by Weldify** [comment]
I disagree. I currently use this (I wrote a library for it) and so do multiple other people. Its not possible to just grab the component from an entity because multiple components of the same type can exist at once.

I know you previously said that components aren't meant to be used like that, but that's how I use them, and out of all the available options for my use case its the nicest one. The engine should cater towards how developers use things, not the other way around. I find it unfair for this issue to be shot down 5 hours after creation. It didn't have time for anyone to like, dislike, or comment on why this is useful/not useful for someone.

**Comment by xezno** [comment]
> I disagree. I currently use this (I wrote a library for it) and multiple other people have a need for it. Its not possible to just grab the component from an entity because multiple components of the same type can exist at once.

Components are essentially modular parts that can be added to an entity to extend its functionality. Generally, the idea is that an entity has one of each type of component attached. This helps us keep things manageable, predictable, and less prone to bugs.

Components, as you know, are modular parts added to an entity to extend its functionality. Typically, it's assumed an entity has one of each type of component attached. This approach helps maintain manageability and predictability, and reduces the likelihood of bugs.

> I know you previously said that components aren't meant to be used like that, but that's how I use them,

Adding identifiers to components could blur the line between components and entities. It also might suggest that components are being used in ways they were not initially intended for, which could lead to unforeseen complications.

> and out of all the available options for my use case its the nicest one.

For your specific use case with interactables, rather than trying to juggle multiple components, with the context I've been given, I think a better approach could be to just use a simple interface.

```cs
public interface IHasInteractions
{
    List<Interaction> GetInteractions();
    string GetInteractionText();
    // ... etc
}
```

> The engine should cater towards how developers use things, not the other way around. I find it unfair for this issue to be shot down 5 hours after creation. It didn't have time for anyone to like, dislike, or comment on why this is useful/not useful for someone.

I understand your concern about the issue being addressed swiftly. Our intention was not to prevent a thorough discussion but to provide a quick response. People are still welcome to share their insights and thoughts even after the issue has been initially addressed.

From my perspective, and based on my current understanding, it's not clear how adding this feature to the engine would provide a significant benefit. If you really want to do this, you can just add your own identifier to a base class, and fetch the component yourself.

**Comment by Weldify** [comment]
> If you really want to do this, you can just add your own identifier to a base class, and fetch the component yourself.

That's what I currently do. I've tried multiple approaches. and the current implementation (using components) is the nicest one by far.

> From my perspective, and based on my current understanding, it's not clear how adding this feature to the engine would provide a significant benefit.

My use case is just one of a thousand you could come up with. They work really well for this - so not making the most of them would be a shame. Sure, my use case can be implemented differently, but I chose this way, because it's nice - I can see which interactions an entity has right in the editor, I can turn them on/off, I can change what name is displayed for it, all that jazz.

> Adding identifiers to components could blur the line between components and entities. It also might suggest that components are being used in ways they were not initially intended for, which could lead to unforeseen complications.

I don't see how making components more versatile is a bad thing, they are already very flexible - so why not *enable* us to use that flexibility instead of limiting it? I also don't see how adding identifiers to components will introduce any complications - I'm sure you're already using entity-relative id's to keep track of components internally, so why not use that?

**Comment by Weldify** [comment]
Pretty sure, yeah. It works with `[Net]`. From what conna said, the ID already exists but is just internal and is used for RPCs. So I don't see harm in letting us pass components through ConCommands too.

**Comment by kurozael** [comment]
> Didn't @kurozael already make components addressable?

I did indeed, you can use them with `[Net]` and they they have a unique identifier primarily just for use with RPCs. The identifier is internal because it's supposed to only be used to find the component during the invocation of an RPC upon one.

Though I do get the feeling you may trying to use entity components for purposes outside of their intended scope, @Weldify.

**Comment by Weldify** [comment]
That's true, I use them very extensively and you might consider that out-of-scope, however I found that to be very flexible, simple and nice to use overall. I would like you guys to support my use case.

**Comment by Weldify** [comment]
I referred to my use case for components - instantiating multiple of them on the same entity at times. Isn't this why this issue was closed in the first place; because you guys don't want people to use components that way..?

> Sounds like misuse, components shouldn't be uniquely identifiable

**Comment by handsomematt** [comment]
From my perspective it's only gonna further enable what I see as bad complex design for stuff that could be done much simpler - but I'd leave it up to @kurozael on whether to add it or not as he's the most experienced with this stuff.

**Comment by Weldify** [comment]
I understand that you might think it's bad - but I'm using it and from experience I can say it's nice to use. I love to see my components in the editor and be able to edit them, turn em on or off. 

There isn't anything objectively bad about my use case. There's a nice thing I'm making use of. If you don't like it because you'd do it differently, that's fine - but disregarding it entirely is unfair considering you haven't used tried using it that way for yourself.

**Comment by garrynewman** [comment]
Multiple of the same components on an entity should definitely be supported and won't ever go away

**Comment by kurozael** [comment]
Unfortunately it's my view that supporting this will further enable an unnecessarily complicated design. I've already added support for some of your previous suggestions, such as using `[Net]` with a component because I think that makes sense. However, passing a Component via a ConCommand seems unnecessary.

If you want to continue with this design, I don't see why you couldn't have a base component type that stores your own unique `[Net]` identifier. You could then send via a ConCommand the entity index, and that identifier.

**Comment by Weldify** [comment]
I agree with you! What I need is to pass a component reference from the client to the server. I asked for it to be added to ConCommand because ServerRPC isn't a thing yet, but I definitely wouldn't mind just passing the unique ID of a component.

In this case, what I'm looking for is a way to get the unique ID of a component and get a component from that ID, just like what entities currently have: `Entity.NetworkIdent` and `Entity.FindByIndex()`

**Comment by yuberee** [comment]
This conversation is silly, Weldify is using ConCmd because ServerRPC hasn't been implemented yet, it's not like he wants players to write commands in their console to interact with components.
I say just exposing the component ID should be enough, it's not necessary but it would be nice to have.

**Comment by matekdev** [comment]
> This conversation is silly, Weldify is using ConCmd because ServerRPC hasn't been implemented yet, it's not like he wants players to write commands in their console to interact with components.
> I say just exposing the component ID should be enough, it's not necessary but it would be nice to have.

Yeah it would be nice if component ID was exposed so we could look it up during a ConCmd.

I had a use case where a single component was created on every weapon entity in my game. The player could grab a reference to each component and store it into a list. I needed a way to identify each component uniquely.

I wrote my own tiny solution, but it would be nice if it was exposed.

**Comment by kurozael** [comment]
We don't currently have any plans to expose a unique identifier for components in the API. We might re-evaluate that in the future as systems are iterated on and evolve over time.

If you would like to reference components by a unique identifier, I would suggest creating an interface called IUniqueComponent with a ComponentId property, and implementing that in your component with the [Net] attribute. When you create your component server-side, you can set it to a unique value - perhaps by incrementing a static integer.

This way you would be able to find the component on an entity in future by searching through its components to find one with that identifier.

**Comment by Weldify** [comment]
Up until this is added to the engine, I will be actively maintaining my implementation of this. It's an open-source library, currently available under `sfl.ucom`
https://github.com/SaveFileLost/ucom
