### ISSUE TITLE
Ability to get the rendered WorldPanel/Panel onto a Texture similiar to VideoPlayer

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#3689]
### For?

S&Box

### What can't you do?

At the moment, I can't seem to find a way to render the contents of a panel/worldpanel onto a texture. The point of this is being able to render panels on a curved surface in the world, such as monitors with non-flat screens.

### How would you like it to work?

Similiarly to `VideoPlayer`, it could provide a Texture containing the rendered panel.

### What have you tried?

Having a flat screen, but can't have custom surfaces with custom geo and UV mapping.

**Comment by chrisspieler** [comment]
So, this could be very useful for the Cinema game. 

We currently have a projector that's essentially just a spotlight with a VideoPlayer texture as a light cookie. We'd like to overlay panels on top of the video texture.

This feature request would let us accomplish this goal by doing the following:
1. Make a panel with the background set to the VideoPlayer texture.
2. In the foreground of the panel, draw various different elements as necessary:
    - A pause/resume bubble, similar to what you'd see on YouTube
    - A spinning wheel when buffering
    - A progress bar that appears temporarily when seeking or paused
    - A volume bar that appears when pressing some "change media volume" shortcut
    - Closed captions
3. Take the texture of the panel and set it to the light cookie of the projector

This would essentially give us a very versatile way of compositing videos and images in to a texture for whatever purpose. I think this is better than just putting a WorldPanel at the screen position since:
  - It is guaranteed to actually line up properly with the video.
  - Walking in front of the projected light to cast a shadow will hide the UI as well as the video.
  - We don't have to worry about depth issues.

I think the workaround to not having this feature is to make a WorldPanel in a SceneWorld, use RenderToTexture, and put the panel's texture over the video texture in a compute shader or Texture.Update. Or just use a WorldPanel over the screen, which has the limitations I previously mentioned. In any case, it would be really great if we could get the UI system do the heavy lifting.

**Comment by CarsonKompon** [comment]
This would be fantastic for things such as my arcade machines where the game is (currently) a WorldPanel floating just barely in front of the screen. However, if I could get a texture from a Panel, then I could render the game directly to the arcade screen instead of having it float without having any material properties (like LCD screen and so on)

**Comment by e1m1j** [comment]
Commenting because this would be really useful to have.

**Comment by ShadowBrian** [comment]
Commenting because this would be really useful to have also.

**Comment by aylaylay** [comment]
Me and @handsomematt discussed this. It was decided for flexibility to add ```RootPanel.RenderManual``` instead of jamming this into world panel. This allows you to control where the panel is rendered to, including rendering to texture. Here's an example of how to do it.

https://gist.github.com/aylaylay/52b51f5a03ade8f510e15221b00476f0

Basically you just want to do
```cs
Graphics.RenderTarget = RenderTarget.From( Texture );
Graphics.Attributes.SetCombo( "D_WORLDPANEL", 0 );
Graphics.Viewport = new Rect( 0, Panel.PanelBounds.Size );
Graphics.Clear();

Panel.RenderManual();

Graphics.RenderTarget = null;
```

Inside of a render block, your texture now has the UI

**Comment by GNUGradyn** [comment]
Is this still possible? Your example references several classes that no longer exist
