### ISSUE TITLE
Ability to return the Discord Role (if the person left the Discord server and returned)

### ISSUE THREAD

**Issue by Laefye** [sboxgame/issues#3714]
### For?

Other

### What can't you do?

There is no way to get your role back, if anyone left from the discord server and joined back

### How would you like it to work?

After the person joined the discord server, the bot (which gives roles) checked whether he had already got the role earlier

### What have you tried?

Wait...

**Comment by robotboy655** [comment]
Does going to `asset.party` => `Profile` => `Discord` and following the instructions not work a second time?

**Comment by yuberee** [comment]
Never has afaik, people usually just ask Facepunch to manually set their role when that happens.
That or they use an alt account on Steam to redeem and Invite Code and then use their main Discord ID to get the rank again, but it's mildly inconvenient.

**Comment by Laefye** [comment]
@robotboy655 
![image](https://github.com/sboxgame/issues/assets/24413784/6f361616-ee55-4289-bb89-10d93bcf8e07)
There is no way to repeat the process or something like that (I got the role before I left the discord server)

**Comment by robotboy655** [comment]
I have added a button to that page that will reapply the role to the Discord account you gave it earlier, let me know if it doesn't work.

**Comment by Laefye** [comment]
Yeah, it works, thanks! ❤️

**Comment by DarkReaper231** [comment]
> I have added a button to that page that will reapply the role to the Discord account you gave it earlier, let me know if it doesn't work.

This created a huge flaw. I accidentally typed in wrong ID when linking my Discord account with asset.party and the website does not allow unlinking.

I gave the guy who I linked my asset.party account to accidentally one of my s&box keys. I told him to link his Discord ID hoping it will automatically unlink my asset.party account from his Discord account. That did not happen. His Discord account now apparently has two asset.party accounts linked to it which may have created a conflict in the database.

There should be unlink button for Discord. Slap a message saying: "Sorry you can't link another account because your previous account was banned" if that's a concern but let people who did not get banned change their Discord ID there.

**Comment by robotboy655** [comment]
Nah, that issue would be there without the newly added button.

Checking if a Discord ID is already associated with someone, while logical, would not prevent people from randomly linking someone else's ID, unless you have hit the very unlikely chance of entering an already associated ID.

The problem with an "Unlink" option is that you could give the roles to any number of accounts. I do not see much of a reason to invest time in keeping track who was banned from Discord who also has an asset.party account or anything of the sort, given that this system is temporary and will most likely be removed when the game releases.

You could give me your Discord ID so I could assign you the role, or your SteamID and I will see what I can do for you to "unlink" your account.

**Comment by robotboy655** [comment]
I have reset Discord ID for you, you should be able to enter a new one.

**Comment by DarkReaper231** [comment]
Works! Thank you very much!

**Comment by SolsticeSpectrum** [comment]
@robotboy655 Hi, sorry for this but I had to delete my discord account because I got doxed and was getting mass amounts of spams from random people. I have a new account but this poses an issue again. I can't reset my Discord ID. Could you please reset it again for me? My new Discord ID is `thedumbdude`, the old one is deleted.
