### ISSUE TITLE
Better Optimisation

### ISSUE THREAD

**Issue by UnderCurve** [sboxgame/issues#3836]
### For?

S&Box

### What can't you do?

I would just like to request some better optimisation options or smth like that so the game can run better on lower end hardware

### How would you like it to work?

Just like add more options to the video/graphic settings so you can your able to get more fps on lower end hardware

### What have you tried?

Nothing really because I'm not sure how to optimize S&box that much

**Comment by rndtrash** [comment]
Hi, have you tried changing the graphics settings or changing the console variables that start with `r_`?

Here are some of the console variables that can give you a little performance boost: https://steamcommunity.com/sharedfiles/filedetails/?id=2609627468

Beware, though: not all of them might work, since this game is still in heavy development!

**Comment by DevulTj** [comment]
this is a given
